### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by welblaud** [voikya/swordfish#11]
I am really keen on Swordfish, I'd been searching for such an utility for ages!

However, is there any way how to preserve another languages next to English?

When I am parsing a Czech file, the result includes many errors on diacritical marks places...

I am sorry I am writing my question here, don't now how to do that better. It could be a feature request!

Thanks!

**Comment by voikya** [comment]
Hi, I tried some simple conversions using UTF-8 and they seemed to work correctly. I noticed you closed this issue; did you find a workaround? If not, could you provide a simple sample document that isn't parsed correctly?

**Comment by welblaud** [comment]
Hi, the problem was in the most simplest thing - the charset declaration in the output. I have forked and will try to do a tidier HTML result. Its not important for viewing the result in browser but the code itself. Honestly, I am very keen on Swordfish, I will try to use it for my project in a publishing house. Until now I had been using the docx gem but it has much less abilities. Thanks for the nice gem!
